"""
Validation limits used across the application.
"""

COMPANY_NAME_MAX_LENGTH = 255

DESCRIPTION_MAX_LENGTH = 1000

PHONE_MAX_LENGTH = 20

EMAIL_MAX_LENGTH = 255

GST_NUMBER_LENGTH = 15

LICENSE_NUMBER_MAX_LENGTH = 100

MATERIAL_NAME_MAX_LENGTH = 255

QUALITY_GRADE_MAX_LENGTH = 20